import { PropertyInvestor } from "@/types/dashboardTypes";

export const investorProperties: PropertyInvestor[] = [
  {
    id: "1",
    name: "Sunset Apartments",
    description: "A luxurious apartment complex with stunning sunset views.",
    location: "Los Angeles, CA",
    tokenOwn: "500",
    withdrawLimit: "100",
    withdrawn: "50",
    status: "Verified",
  },
  {
    id: "2",
    name: "Greenfield Villas",
    description: "Eco-friendly villas surrounded by lush greenery.",
    location: "Austin, TX",
    tokenOwn: "300",
    withdrawLimit: "80",
    withdrawn: "30",
    status: "Verified",
  },
  {
    id: "3",
    name: "Oceanview Condos",
    description: "Modern condos with breathtaking ocean views.",
    location: "Miami, FL",
    tokenOwn: "400",
    withdrawLimit: "120",
    withdrawn: "60",
    status: "Not Verified",
  },
  {
    id: "4",
    name: "Downtown Lofts",
    description: "Stylish lofts in the heart of the city.",
    location: "New York, NY",
    tokenOwn: "600",
    withdrawLimit: "150",
    withdrawn: "100",
    status: "Verified",
  },
  {
    id: "5",
    name: "Mountain Retreat",
    description: "A peaceful retreat in the mountains.",
    location: "Denver, CO",
    tokenOwn: "250",
    withdrawLimit: "70",
    withdrawn: "20",
    status: "Not Verified",
  },
  {
    id: "6",
    name: "Lakeside Residences",
    description: "Beautiful residences by the lake.",
    location: "Seattle, WA",
    tokenOwn: "350",
    withdrawLimit: "90",
    withdrawn: "40",
    status: "Verified",
  },
];
