import { Property } from "@/types/propertyDashboardTypes";

export const properties: Property[] = [
  {
    id: "1",
    name: "G&B House",
    description: "A beautiful house in Surakarta",
    location: "Surakarta",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Verified",
  },
  {
    id: "2",
    name: "Lotus Villa",
    description: "Cozy villa with garden view",
    location: "Bandung",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Not Verified",
  },

  {
    id: "3",
    name: "Sunset Apartment",
    description: "Modern apartment with city view",
    location: "Jakarta",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Verified",
  },
  {
    id: "4",
    name: "Ocean Breeze Cottage",
    description: "Cozy cottage near the beach",
    location: "Bali",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Not Verified",
  },
  {
    id: "5",
    name: "Mountain Retreat",
    description: "Peaceful retreat in the mountains",
    location: "Malang",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Verified",
  },
  {
    id: "6",
    name: "City Center Loft",
    description: "Stylish loft in the heart of the city",
    location: "Yogyakarta",
    rate: "4 %",
    availableTokens: "100 LLoT",
    remainingDebt: "100 USDC",
    status: "Not Verified",
  },
];
